# Generated by Django 5.2.15 on 2026-06-15 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('temperature', models.FloatField(default=0.2)),
                ('system_prompt', models.TextField()),
                ('function_calling_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
