# Generated by Django 5.2.15 on 2026-06-15 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_override', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('ai', 'AI'), ('operator', 'Operator'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('manual', 'Manual')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(default='active', max_length=64)),
                ('detected_language', models.CharField(blank=True, max_length=20)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('operator_needed', models.BooleanField(default=False)),
                ('ai_paused_until', models.DateTimeField(blank=True, null=True)),
                ('ai_pause_reason', models.CharField(blank=True, max_length=255)),
                ('last_operator_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
