# Generated by Django 5.2.15 on 2026-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_ai_processed_customer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_customer_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatFollowUp',
        ),
    ]
