"""give ai_messages a total order that created_at never was

The transcript was ordered by `created_at`, which is `server_default=func.now()`
— and Postgres `now()` is the *transaction* timestamp, not the statement's. One
assistant request writes the visitor's row and the model's answer inside a
single transaction, so the two rows come out of the database carrying
byte-identical timestamps. `ORDER BY created_at` therefore has no defined order
*within* a turn; it returns the tied pair in whatever order the heap hands them
over.

That was survivable while every read was `asc()`. It stopped being survivable
when the model-history window became "newest twenty, reversed": the reverse
flips each tied pair, and the model was handed its own reply *before* the
question it answered. Reproduced on a production-shaped scratch database — 12
turns, each one transaction, a second apart — as
`['q3','a3','a4','q4','a5','q5','q6','a6', ...]`: 4 of the 10 turns in the
window inverted. A UUIDv4 primary key is random, so `id` could only have made
that deterministic, not correct.

`seq` is generated at INSERT time rather than at COMMIT time, so it separates
two rows of one transaction in the order they were added — which is the order
they were said in. GENERATED BY DEFAULT (`always=False`) rather than ALWAYS, so
the backfill below and any future repair script can write the column without
having to override the identity.

The backfill orders by `created_at`, then by role with `user` first, then by
`id`. The role rank is the whole point: within one tied timestamp the only
thing that survives about the pair is that a visitor's turn preceded the answer
to it, and that is what gets written down. `id` is the last term purely so the
statement is deterministic if it is ever re-run — it is not meaningful.

The order of the three steps is forced and worth reading once. The column
arrives nullable, because an existing table cannot be handed a NOT NULL column
with no value for the rows already in it. It becomes NOT NULL next, because
Postgres refuses `ADD GENERATED ... AS IDENTITY` on a nullable column
("column \"seq\" of relation \"ai_messages\" must be declared NOT NULL before
identity can be added"). The identity is attached last, started past the largest
number the backfill wrote, so the first message stored after this deploy cannot
be handed a number a historical row already holds.

The unique index is on `(session_id, seq)` rather than on `seq` alone. `seq` is
globally unique anyway, so the composite adds no constraint the identity does
not already give — what it adds is the read: "the newest twenty rows of this
conversation" becomes an index scan instead of sorting the session's messages.
`ix_ai_messages_session_time` stays, because the daily-quota count and the
panel's "last activity" both still ask about time.

This revision does take the table out of service for the length of it: the
backfill rewrites every row, and SET NOT NULL, ADD GENERATED and CREATE INDEX
each take an ACCESS EXCLUSIVE lock. That is stated rather than worked around
because `ai_messages` is a chat widget's transcript, not a ledger — it is small
enough that the whole thing is a blink, and a transcript that is briefly
unreadable is a far smaller problem than one that is permanently out of order.

Revision ID: a3c92f7e5d18
Revises: f4a1c8e02d73
Create Date: 2026-09-07
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a3c92f7e5d18'
down_revision = 'f4a1c8e02d73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Nullable first: an existing table cannot be handed a NOT NULL column
    # without a value for every row already in it.
    op.add_column('ai_messages', sa.Column('seq', sa.BigInteger(), nullable=True))

    # Deterministic backfill. `user` before anything else inside one tied
    # timestamp, because a question precedes its answer; `id` last only so a
    # re-run produces the same numbers.
    op.execute(
        """
        UPDATE ai_messages AS m
           SET seq = ordered.rn
          FROM (
                SELECT id,
                       row_number() OVER (
                           ORDER BY created_at,
                                    CASE WHEN role = 'user' THEN 0 ELSE 1 END,
                                    id
                       ) AS rn
                  FROM ai_messages
               ) AS ordered
         WHERE m.id = ordered.id
        """
    )

    # NOT NULL before the identity, not after: Postgres rejects
    # `ADD GENERATED ... AS IDENTITY` on a column that still allows NULL.
    op.alter_column('ai_messages', 'seq', existing_type=sa.BigInteger(), nullable=False)

    # Start the identity past everything the backfill wrote, so the next
    # message stored cannot be handed a number a historical row already holds.
    # On a fresh database MAX is NULL and this starts at 1.
    op.execute(
        """
        DO $$
        DECLARE next_seq bigint;
        BEGIN
            SELECT COALESCE(MAX(seq), 0) + 1 INTO next_seq FROM ai_messages;
            EXECUTE format(
                'ALTER TABLE ai_messages '
                'ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY '
                '(START WITH %s)',
                next_seq
            );
        END $$;
        """
    )
    op.create_index(
        'ix_ai_messages_session_seq', 'ai_messages', ['session_id', 'seq'], unique=True
    )


def downgrade() -> None:
    # Dropping the column drops its identity sequence with it, so the order
    # every reader downstream of this revision depends on goes back to being
    # undefined within a turn. Nothing else here can reconstruct it.
    op.drop_index('ix_ai_messages_session_seq', table_name='ai_messages')
    op.drop_column('ai_messages', 'seq')
