# Generated by Django 5.2.15 on 2026-06-15 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('total_credit_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_daily_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cash_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_card_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_card_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_dollar_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_dollar_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dollar_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('plastic_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('passed_card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('passed_dollar_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debtor_type', models.CharField(choices=[('solar_panel', 'Solar Panel'), ('moto_business', 'Moto Business')], max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('neighborhood', models.CharField(max_length=120)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('debt_taken_on', models.DateField()),
                ('repayment_due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='metadata',
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='cadastre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='card_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='client',
            name='hokim_helper_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='hokim_helper_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='pnfl',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('credit_expense', 'Kredit расход'), ('daily_expense', 'Кунлик чиким'), ('cash_income', 'Кирим накд'), ('card_income', 'кирим П.К'), ('card_expense', 'чиким П.К'), ('dollar_income', 'Доллир кирим'), ('dollar_expense', 'Доллир чиким')], max_length=32)),
                ('counterparty_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='clients.accountingday')),
            ],
            options={
                'ordering': ('accounting_day', 'category', 'sort_order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.clientstatus'),
        ),
    ]
