# Generated by Django 5.2.15 on 2026-06-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_company_add_sales_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatus',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
