# Generated by Django 5.2.15 on 2026-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientstatus_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingentry',
            name='accounting_day',
        ),
        migrations.DeleteModel(
            name='Debtor',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='auditor_company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='auditor_company_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_branch_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cadastre',
        ),
        migrations.RemoveField(
            model_name='client',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='district',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hokim_helper_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hokim_helper_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pnfl',
        ),
        migrations.RemoveField(
            model_name='client',
            name='requested_kw',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subsidy_amount',
        ),
        migrations.AddField(
            model_name='client',
            name='interested_product',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='AccountingDay',
        ),
        migrations.DeleteModel(
            name='AccountingEntry',
        ),
    ]
